[workspace]
resolver = "3"
members = [
  "crates/protocol",
  "crates/server",
  "crates/sdk",
  "crates/client",
  "crates/app",
]

[workspace.package]
version = "1.1.1"
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.94.1"
authors = ["Richard Osterloh <richard.osterloh@gmail.com>"]

[workspace.dependencies]
anyhow = "1.0.104"
async-trait = "0.1.91"
bluer = { version = "0.17.4", features = ["bluetoothd", "l2cap"] }
btleplug = "0.12.0"
ciborium = "0.2.2"
clap = { version = "4.6.4", features = ["derive"] }
futures-util = "0.3.33"
hmac = "0.12.1"
ipnet = "2.12.0"
proptest = "1.11.0"
rand = "0.10.2"
sd-notify = "0.5.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_bytes = "0.11.19"
sha2 = "0.10.9"
subtle = "2.6.1"
thiserror = "2.0.19"
tokio = { version = "1.53.1", features = [
  "rt-multi-thread",
  "macros",
  "sync",
  "time",
  "io-util",
  "fs",
  "signal",
] }
tokio-util = { version = "0.7.19", features = ["codec"] }
tracing = "0.1.44"
tracing-journald = "0.3.2"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt"] }
uuid = "1.22.0"

[profile.release]
lto = "thin"
strip = true
